#!/usr/bin/guile -s 
#
# tg-build
# Wrapper which walks through all modularized scripts
# 
# This file is part of Thermograph.
# 
# Thermograph is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Thermograph is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Thermograph. If not, see <http://www.gnu.org/licenses/>.
# 
# Copyright 2016 Martin Michel

!#
;;;coding:utf-8

;;; Use UTF-8 
(setlocale LC_ALL "")
(use-modules (ice-9 regex))
(use-modules (srfi srfi-1))

(load "scripts/utils.scm")
;(define bcs/cc #f)

;(define model
;  (lambda (name)
;    (call/cc (lambda (k) (set! bcs/cc k)))))
;
(load "scripts/bcs-inject.scm")
;(load "scripts/bcs.scm")
(load "scripts/valve-inject.scm")
(load "scripts/header-inject.scm")

(load "def.scm") 

(load "scripts/to-header.scm")
(load "scripts/to-thermograph.scm")
(load "scripts/to-model-f.scm")
(load "scripts/to-model-df.scm")
(load "scripts/to-model-fdf.scm")
